/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#000000",
        "inverse-primary": "#bfc1ff",
        error: "#ba1a1a",
        "surface-container-highest": "#d5e3fc",
        "surface-bright": "#f8f9ff",
        "tertiary-fixed-dim": "#c3c0ff",
        "error-container": "#ffdad6",
        "on-secondary-container": "#0e6081",
        "surface-variant": "#d5e3fc",
        outline: "#777683",
        "on-primary-fixed": "#070666",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#c3e8ff",
        "on-surface": "#0d1c2e",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#7a78e1",
        "on-primary-container": "#777cd3",
        secondary: "#186586",
        primary: "#000000",
        "surface-container-high": "#dce9ff",
        "on-tertiary-fixed": "#0f0069",
        "outline-variant": "#c7c5d3",
        "on-primary-fixed-variant": "#393d91",
        "secondary-fixed-dim": "#8dcff3",
        "primary-fixed": "#e1e0ff",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#004c68",
        "on-surface-variant": "#464651",
        "tertiary-fixed": "#e2dfff",
        "on-secondary-fixed": "#001e2c",
        "on-background": "#0d1c2e",
        "inverse-surface": "#233144",
        "tertiary-container": "#0f0069",
        surface: "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "surface-tint": "#5156aa",
        "secondary-container": "#99daff",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#3c379f",
        "surface-container": "#e6eeff",
        "primary-container": "#070666",
        "surface-dim": "#ccdbf3",
        background: "#f8f9ff",
        "primary-fixed-dim": "#bfc1ff",
        "surface-container-lowest": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-md": "0.75rem",
        gutter: "1rem",
        "gutter-dense": "0.5rem",
        "space-lg": "1.25rem",
        "space-xl": "1.75rem",
        margin: "1.5rem",
        "space-sm": "0.5rem",
        "space-2xl": "2.5rem",
      },
      fontFamily: {
        "label-md": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-xs": ["Inter"],
        "display-lg": ["Plus Jakarta Sans"],
        "label-lg": ["Inter"],
        "display-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "code-num": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "label-md": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-lg": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-lg": [
          "22px",
          { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-xs": [
          "10px",
          { lineHeight: "12px", letterSpacing: "0.04em", fontWeight: "700" },
        ],
        "display-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-lg": [
          "13px",
          { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "display-md": [
          "26px",
          { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" },
        ],
        "headline-sm": [
          "16px",
          { lineHeight: "22px", fontWeight: "600" },
        ],
        "code-num": [
          "13px",
          { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "headline-md": [
          "18px",
          { lineHeight: "24px", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
